---
- name: Auditoría Tema 1 - Introducción a GNU/Linux
  hosts: auditadas
  become: yes
  gather_facts: no
  vars:
    tema_id: "tema1"

  tasks:

    # ==========================================
    # Inicialización (para evitar variables undefined)
    # ==========================================
    - name: Inicializar estructura de resultados
      set_fact:
        checks: {}
      changed_when: false

    # =========================
    # PRUEBA 1 - Sudo instalado
    # =========================
    - name: "[Prueba 1] Comprobar si sudo está instalado"
      command: dpkg -l sudo
      register: sudo_check
      ignore_errors: yes
      changed_when: false

    - name: "[Prueba 1] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'1': {'name': 'sudo instalado', 'ok': (sudo_check.rc == 0)}}) }}"
      changed_when: false

    # ======================================
    # PRUEBA 2 - Root no por defecto (shadow)
    # ======================================
    - name: "[Prueba 2] Comprobar hash de root en /etc/shadow"
      command: grep '^root:' /etc/shadow
      register: root_shadow
      changed_when: false

    - name: "[Prueba 2] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'2': {'name': 'root configurado (hash distinto de !)', 'ok': ((root_shadow.stdout.split(':')[1] | default('')) != '!')}}) }}"
      changed_when: false

    # =========================================
    # PRUEBA 3 - Usuario adminpas en grupo sudo
    # =========================================
    - name: "[Prueba 3] Comprobar usuario adminpas"
      command: getent passwd adminpas
      register: admin_user
      ignore_errors: yes
      changed_when: false

    - name: "[Prueba 3] Comprobar grupo sudo"
      command: getent group sudo
      register: sudo_group
      changed_when: false

    - name: "[Prueba 3] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'3': {'name': 'usuario adminpas existe y está en grupo sudo', 'ok': (admin_user.rc == 0 and 'adminpas' in (sudo_group.stdout | default('')))}}) }}"
      changed_when: false

    # ==========================
    # PRUEBA 4 - Servicio SSH (SOLO COMPROBAR)
    # ==========================
    - name: "[Prueba 4] Obtener facts de servicios"
      service_facts:

    - name: "[Prueba 4] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'4': {'name': 'servicio SSH activo', 'ok': (((ansible_facts.services['ssh.service'].state | default('')) == 'running') or ((ansible_facts.services['sshd.service'].state | default('')) == 'running'))}}) }}"
      changed_when: false

    # ==========================================
    # PRUEBA 5 - Sólo terminal (sin entorno gráfico)
    # ==========================================
    - name: "Comprobar paquetes gráficos instalados"
      package_facts:
        manager: auto

    - name: "Comprobar si hay servidor X instalado"
      set_fact:
        has_x_server: "{{ ('xserver-xorg' in ansible_facts.packages) or ('xorg' in ansible_facts.packages) }}"
      changed_when: false

    - name: "Verificar servicios de gestión gráfica"
      command: systemctl list-units --type=service --no-pager
      register: services_graphic
      changed_when: false
      failed_when: false

    - name: "Establecer presencia de servicios gráficos"
      set_fact:
        has_graphic_service: "{{ ('gdm.service' in (services_graphic.stdout | default(''))) or ('lightdm.service' in (services_graphic.stdout | default(''))) or ('sddm.service' in (services_graphic.stdout | default(''))) or ('xdm.service' in (services_graphic.stdout | default(''))) }}"
      changed_when: false

    - name: "Comprobar si Xorg está presente en el sistema"
      command: "which Xorg"
      register: which_xorg
      failed_when: false
      changed_when: false

    - name: "[Prueba 5] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'5': {'name': 'solo terminal (sin entorno gráfico)', 'ok': (not (has_x_server or has_graphic_service or which_xorg.rc == 0))}}) }}"
      changed_when: false

    # ==============================
    # PRUEBA 6 - Sistema actualizado
    # ==============================
    - name: "[Prueba 6] Comprobar actualizaciones pendientes"
      command: apt list --upgradable
      register: updates
      changed_when: false

    - name: "[Prueba 6] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'6': {'name': 'sistema actualizado (sin upgradables)', 'ok': ((updates.stdout_lines | length) <= 1)}}) }}"
      changed_when: false

    # ==========================
    # SCORE FINAL (SIN variables intermedias)
    # ==========================
    - name: Calcular score final
      set_fact:
        total_checks: "{{ checks | length }}"
        passed_checks: "{{ (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int }}"
        percent_score: "{{ (( (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int ) * 100 / ((checks | length) | int if ((checks | length) | int) > 0 else 1)) | round(0) | int }}"
      changed_when: false

    - name: Mostrar resultados (resumen)
      debug:
        msg:
          - "Tema: {{ tema_id }} Host: {{ inventory_hostname }}"
          - "{% for item in (checks | dict2items | sort(attribute='key')) %}Prueba {{ item.key }} ({{ item.value.name }}): {{ 'CORRECTO' if item.value.ok else 'INCORRECTO' }}{% if not loop.last %}\n{% endif %}{% endfor %}"
          - "SCORE: {{ passed_checks }}/{{ total_checks }} ({{ percent_score }}%)"

    # ==========================
    # EXPORTAR CSV en AUDITORA
    # ==========================
    - name: Exportar CSV en la máquina auditora
      import_tasks: /home/tfg-audit/hosts/export_csv.yml
      vars:
        checks: "{{ checks }}"
        passed_checks: "{{ passed_checks }}"
        total_checks: "{{ total_checks }}"
        percent_score: "{{ percent_score }}"
