---
- name: Auditoría Tema 2 - Organización del sistema
  hosts: auditadas
  become: yes # Necesario para acceder a directorios protegidos
  gather_facts: no

  vars:
    tema_id: "tema2"

  tasks:
    # ==========================================
    # Inicialización
    # Creamos el diccionario checks vacio para evitar errores de variables no definidas, 
    #aqui es donde añadimos los resultados de cada prueba
    # ==========================================
    - name: Inicializar estructura de resultados
      set_fact:
        checks: {}
      changed_when: false

    #################################
    # PRUEBA 1 - Permisos claves .ssh
    # Se comprueban los permisos de:
    #   - /root/.ssh
    #   - /home/adminpas
    #   - /home/adminpas/.ssh
    #
    # Requisitos:
    #   - /root/.ssh          -> 0700
    #   - /home/adminpas      -> 0755
    #   - /home/adminpas/.ssh -> 0700
    #
    # CORRECTO solo si:
    #   - todos los directorios existen
    #   - todos tienen exactamente los permisos esperados
    #################################

    - name: "[Prueba 1] Comprobar permisos /root/.ssh"
      stat:
        path: /root/.ssh
      register: root_ssh
      failed_when: false
      changed_when: false

    - name: "[Prueba 1] Comprobar permisos /home/adminpas"
      stat:
        path: /home/adminpas
      register: home_admin
      failed_when: false
      changed_when: false

    - name: "[Prueba 1] Comprobar permisos /home/adminpas/.ssh"
      stat:
        path: /home/adminpas/.ssh
      register: admin_ssh
      failed_when: false
      changed_when: false

    - name: "[Prueba 1] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '1': {
                'name': 'permisos claves .ssh (root y adminpas)',
                'ok': (
                  (root_ssh.stat.exists | default(false)) and
                  (home_admin.stat.exists | default(false)) and
                  (admin_ssh.stat.exists | default(false)) and
                  ((root_ssh.stat.mode | default('')) == '0700') and
                  ((home_admin.stat.mode | default('')) == '0755') and
                  ((admin_ssh.stat.mode | default('')) == '0700')
                )
              }
            })
          }}
      changed_when: false

    #################################
    # PRUEBA 2 - Permisos /var/www para grupo web
    # Requisitos:
    #   - El directorio /var/www debe existir
    #   - Propietario: root
    #   - Grupo: web
    #   - Permisos: 0775
    #
    # CORRECTO solo si:
    #   - existe el directorio
    #   - permisos, usuario y grupo coinciden exactamente

    #################################

    - name: "[Prueba 2] Comprobar /var/www"
      stat:
        path: /var/www
      register: www_dir
      failed_when: false
      changed_when: false

    - name: "[Prueba 2] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '2': {
                'name': '/var/www con grupo web (0775 root:web)',
                'ok': (
                  (www_dir.stat.exists | default(false)) and
                  ((www_dir.stat.mode | default('')) == '0775') and
                  ((www_dir.stat.pw_name | default('')) == 'root') and
                  ((www_dir.stat.gr_name | default('')) == 'web')
                )
              }
            })
          }}
      changed_when: false

    # ==========================
    # SCORE FINAL
    # Se calcula el total de pruebas, el numero de pruebas correctas y el porcentaje obtenido
    # ==========================
    - name: Calcular score final
      set_fact:
        total_checks: "{{ checks | length }}"
        passed_checks: "{{ (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int }}"
        percent_score: "{{ (( (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int ) * 100 / ((checks | length) | int if ((checks | length) | int) > 0 else 1)) | round(0) | int }}"
      changed_when: false

    - name: Mostrar resultados (resumen)
      debug:
        msg: |
          Tema: {{ tema_id }} Host: {{ inventory_hostname }}
          {% for item in (checks | dict2items | sort(attribute='key')) %}
          Prueba {{ item.key }} ({{ item.value.name }}): {{ 'CORRECTO' if item.value.ok else 'INCORRECTO' }}
          {% endfor %}
          SCORE: {{ passed_checks }}/{{ total_checks }} ({{ percent_score }}%)

    # ==========================
    # EXPORTAR CSV (máquina auditora)
    # Se exportan los resultados a CSV en la maquina auditora usando un script
    # ==========================
    - name: Exportar CSV en la máquina auditora
      import_tasks: /home/tfg-audit/hosts/export_csv.yml
      vars:
        checks: "{{ checks }}"
        passed_checks: "{{ passed_checks }}"
        total_checks: "{{ total_checks }}"
        percent_score: "{{ percent_score }}"
