
---
- name: Tema 5 - Gestión de recursos del sistema
  hosts: auditadas

  # Necesitamos privilegios para:
  # - leer límites del sistema
  # - acceder al crontab de root
  # - comprobar logs en /var/log
  become: yes
  gather_facts: no

  vars:
    tema_id: "tema5"

    # Si quieres definir un valor objetivo, ponlo aquí.
    # Si lo dejas en 0, solo comprobamos "no unlimited".
    max_procesos_objetivo: 1000

  tasks:
    # ==========================================
    # Inicialización
    #Creamos el diccionario checks vacio para evitar errores de variables no definidas, 
    #aqui es donde añadimos los resultados de cada prueba
    # ==========================================
    - name: Inicializar estructura de resultados
      set_fact:
        checks: {}
      changed_when: false

    ###########################################################
    # PRUEBA 1 - Límite de procesos de usuario (ulimit -u)
    #
    # REQUISITO:
    #   El número máximo de procesos por usuario debe estar limitado.
    #   No puede ser "unlimited".
    #
    # CÓMO SE GENERA:
    #   Configurando límites en /etc/security/limits.conf
    #
    # CÓMO SE COMPRUEBA:
    #   Ejecutando "ulimit -u".
    #   El valor devuelto debe ser un número (ej. 1000),
    #   y nunca la cadena "unlimited".
    #
    # NOTA:
    #   Usamos "bash -lc" para asegurarnos de que se cargan
    #   correctamente los límites de sesión (PAM).
    ###########################################################

    - name: "[Prueba 1] Leer ulimit -u (max user processes)"
      shell: "bash -lc 'ulimit -u'"
      register: ulimit_u
      failed_when: false
      changed_when: false


    #La prueba es correcta si el valor no es unlimited y es numerico 
    - name: "[Prueba 1] Guardar resultado"
      set_fact:
        checks: "{{ checks | combine({'1': {
          'name': 'ulimit -u limitado (no unlimited)',
          'ok': (
            (ulimit_u.stdout | default('') | trim) != 'unlimited'
            and (ulimit_u.stdout | default('') | trim) is match('^[0-9]+$')
          )
        }}) }}"
      changed_when: false


    #################################
    # PRUEBA 2 - Monitorización memoria (script + cron + log)
    # REQUISITO:
    #   Existe un sistema de monitorización de memoria que:
    #     - ejecuta un script cada 10 minutos
    #     - guarda la memoria física y virtual en un log
    #
    # CÓMO SE GENERA:
    #   - Script en /opt/monitor_memoria/script_memoria.sh
    #   - Script ejecutable
    #   - Entrada en el crontab de root cada */10 minutos
    #   - Log en /var/log/memoria.log
    #
    # CÓMO SE COMPRUEBA:
    #   - El script existe y es ejecutable
    #   - El log existe y no está vacío
    #   - El crontab de root contiene:
    #       */10
    #       /opt/monitor_memoria/script_memoria.sh
    #################################

    # Comprobamos la existencia del script y obtenemos sus permisos
    - name: "[Prueba 2] Stat del script"
      stat:
        path: /opt/monitor_memoria/script_memoria.sh
      register: script_mem
      failed_when: false
      changed_when: false


    # Comprobamos que el log existe y su tamaño
    - name: "[Prueba 2] Stat del log"
      stat:
        path: /var/log/memoria.log
      register: log_mem
      failed_when: false
      changed_when: false


    #Leemos el fichero de crontab de root en formato binario
    - name: "[Prueba 2] Leer crontab de root (archivo Debian)"
      slurp:
        src: /var/spool/cron/crontabs/root
      register: cron_root_file
      failed_when: false
      changed_when: false

    # Decodificamos el crontab si existe
    - name: "[Prueba 2] Decodificar crontab (si existe)"
      set_fact:
        cron_root_text: "{{ (cron_root_file.content | default('') | b64decode) if (cron_root_file is defined and cron_root_file.content is defined) else '' }}"
      changed_when: false



    # La prueba es correcta si tanto el log como el script existen, el script es ejecutable 
    #El log no esta vavio , el crontab contiene la ruta del script y contienen */10 (cada 10 minutos)
    - name: "[Prueba 2] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '2': {
                'name': 'monitorización memoria (script + cron + log)',
                'ok': (
                  (script_mem.stat.exists | default(false))
                  and (script_mem.stat.executable | default(false))
                  and (log_mem.stat.exists | default(false))
                  and ((log_mem.stat.size | default(0) | int) > 0)
                  and ('/opt/monitor_memoria/script_memoria.sh' in (cron_root_text | default('')))
                  and ('*/10' in (cron_root_text | default('')))
                )
              }
            }, recursive=True)
          }}
      changed_when: false

    # ==========================================
    # DEBUG (para confirmar que están 1 y 2)
    # ==========================================
    - name: DEBUG - checks antes del score
      debug:
        var: checks

    # ==========================
    # SCORE FINAL (igual que tema 2)
    # Se calcula el total de pruebas, el numero de pruebas correctas y el porcentaje obtenido
    # ==========================
    - name: Calcular score final
      set_fact:
        total_checks: "{{ checks | length }}"
        passed_checks: "{{ (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int }}"
        percent_score: >-
          {{
            (
              ((checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int) * 100
              / ((checks | length) | int if ((checks | length) | int) > 0 else 1)
            ) | round(0) | int
          }}
      changed_when: false

    - name: Mostrar resultados (resumen)
      debug:
        msg:
          - "Tema: {{ tema_id }} Host: {{ inventory_hostname }}"
          - "{% for item in (checks | dict2items | sort(attribute='key')) %}Prueba {{ item.key }} ({{ item.value.name }}): {{ 'CORRECTO' if item.value.ok else 'INCORRECTO' }}{% if not loop.last %}\n{% endif %}{% endfor %}"
          - "SCORE: {{ passed_checks }}/{{ total_checks }} ({{ percent_score }}%)"

    # ==========================
    # EXPORTAR CSV (máquina auditora)
    # Se exportan los resultados a CSV en la maquina auditora usando un script
    # ==========================
    - name: Exportar CSV en la máquina auditora
      import_tasks: /home/tfg-audit/hosts/export_csv.yml
      vars:
        checks: "{{ checks }}"
        passed_checks: "{{ passed_checks }}"
        total_checks: "{{ total_checks }}"
        percent_score: "{{ percent_score }}"
