---
- name: Tema 8 - Restauración y copias de seguridad
  hosts: auditadas

  # Necesitamos root para:
  # - leer /mnt/backup
  # - ejecutar restore
  # - leer el crontab de root
  become: yes
  gather_facts: no

  vars:
    tema_id: "tema8"

    # Ruta esperada del backup "full" (dump nivel 0)
    dump_file: "/mnt/backup/dump0"

  tasks:
    # ==========================================
    # Inicialización
    # ==========================================
    - name: Inicializar estructura de resultados
      set_fact:
        checks: {}
      changed_when: false

    ##################################################################
    # PRUEBA 1 - Backup dump 
    #
    # REQUISITO:
    #   Debe existir un fichero de dump en /mnt/backup/dump0
    #
    # CÓMO SE PRUEBA :
    #   sudo restore -t -f /mnt/backup/dump0
    #   - Si devuelve "No such file or directory" => no hay backup
    #
    # CORRECTO si:
    #   - existe /mnt/backup/dump0
    #   - /sbin/restore -t -f dump0 devuelve rc=0
    #   - y devuelve varias líneas
    ##################################################################
    - name: "[Prueba 1] Comprobar que existe dump0"
      stat:
        path: "{{ dump_file }}"
      register: dump0_stat
      changed_when: false
      failed_when: false

    - name: "[Prueba 1] Probar restore -t -f dump0 (si existe)"
      command: "restore -t -f {{ dump_file }}"
      register: restore_list
      when: dump0_stat.stat.exists | default(false)
      changed_when: false
      failed_when: false

    - name: "[Prueba 1] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '1': {
                'name': 'backup dump0 existe y restore puede listar',
                'ok': (
                  (dump0_stat.stat.exists | default(false))
                  and ((restore_list.rc | default(1)) == 0)
                  and ((restore_list.stdout_lines | default([])) | length >= 2)
                )
              }
            })
          }}
      changed_when: false

    
    #################################
    # PRUEBA 2 - Backups programados en crontab
    #
    # REQUISITO:
    #   Las copias deben estar programadas.
    #
    # CÓMO SE PRUEBA :
    #   crontab -l debe devolver al menos 2 líneas que NO empiecen por #,
    #   y que contengan la orden dump.
    #
    # CORRECTO si:
    #   - encontramos >=2 líneas activas (no comentadas) que contengan "dump"
    #
    #################################

    - name: "[Prueba 2] Obtener líneas activas de crontab con dump"
      shell: >
        crontab -l 2>/dev/null
        | grep -v '^[[:space:]]*#'
        | grep dump
      register: dump_cron_lines
      failed_when: false
      changed_when: false

    - name: "[Prueba 2] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '2': {
                'name': 'backups programados en crontab (>=2 líneas activas con dump)',
                'ok': ((dump_cron_lines.stdout_lines | length) >= 2)
              }
            })
          }}
      changed_when: false

    # ==========================
    # SCORE FINAL
    # Se calcula el total de pruebas, el numero de pruebas correctas y el porcentaje obtenido
    # ==========================
    - name: Calcular score final
      set_fact:
        total_checks: "{{ checks | length }}"
        passed_checks: "{{ (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int }}"
        percent_score: >-
          {{
            (
              ((checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int) * 100
              / ((checks | length) | int if ((checks | length) | int) > 0 else 1)
            ) | round(0) | int
          }}
      changed_when: false

    - name: Mostrar resultados (resumen)
      debug:
        msg:
          - "Tema: {{ tema_id }} Host: {{ inventory_hostname }}"
          - "{% for item in (checks | dict2items | sort(attribute='key')) %}Prueba {{ item.key }} ({{ item.value.name }}): {{ 'CORRECTO' if item.value.ok else 'INCORRECTO' }}{% if not loop.last %}\n{% endif %}{% endfor %}"
          - "SCORE: {{ passed_checks }}/{{ total_checks }} ({{ percent_score }}%)"

    # ==========================
    # EXPORTAR CSV en AUDITORA
    # Se exportan los resultados a CSV en la maquina auditora usando un script
    # ==========================
    - name: Exportar CSV en la máquina auditora
      import_tasks: /home/tfg-audit/hosts/export_csv.yml
      vars:
        checks: "{{ checks }}"
        passed_checks: "{{ passed_checks }}"
        total_checks: "{{ total_checks }}"
        percent_score: "{{ percent_score }}"
