---
- name: Tema 9 - Gestión de las comunicaciones
  hosts: auditadas
  become: yes
  gather_facts: no

  vars:
    tema_id: "tema9"

    # El hostname debe ser exactamente este 
    required_hostname: "loginpas"

  tasks:
    - name: Inicializar estructura de resultados
      set_fact:
        checks: {}
      changed_when: false

    #################################
    # PRUEBA 1 - Actualizaciones automáticas
    # CORRECTO si:
    #  - paquete unattended-upgrades instalado
    #  - /etc/apt/apt.conf.d/20auto-upgrades contiene las 3 directivas requeridas
    #################################


    - name: "[Prueba 1] ¿Está instalado unattended-upgrades?"
      command: dpkg -s unattended-upgrades
      register: uu_pkg
      failed_when: false
      changed_when: false

    - name: "[Prueba 1] Leer y normalizar /etc/apt/apt.conf.d/20auto-upgrades (quitar espacios)"
      shell: |
        if [ -f /etc/apt/apt.conf.d/20auto-upgrades ]; then
          sed 's/[[:space:]]//g' /etc/apt/apt.conf.d/20auto-upgrades
        fi
      register: uu_norm
      failed_when: false
      changed_when: false

    - name: "[Prueba 1] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '1': {
                'name': 'unattended-upgrades instalado y auto-upgrades configurado',
                'ok': (
                  (uu_pkg.rc == 0)
                  and ('APT::Periodic::Update-Package-Lists"1";' in (uu_norm.stdout | default('')))
                  and ('APT::Periodic::Unattended-Upgrade"1";' in (uu_norm.stdout | default('')))
                  and ('APT::Periodic::AutocleanInterval"7";' in (uu_norm.stdout | default('')))
                )
              }
            })
          }}
      changed_when: false

    #################################
    # PRUEBA 2 - hostname correcto
    
    # CORRECTO si: hostname devuelve "loginpas"
    #################################
    - name: "[Prueba 2] Obtener hostname"
      command: hostname
      register: hostn
      failed_when: false
      changed_when: false

    - name: "[Prueba 2] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '2': {
                'name': 'hostname correcto (' ~ required_hostname ~ ')',
                'ok': ((hostn.stdout | default('') | trim) == required_hostname)
              }
            })
          }}
      changed_when: false

    # ==========================================================
    # PRUEBA 3 - Cortafuegos (ufw)
    #
    # REQUISITO:
    #  - UFW activo
    #  - Default: deny (incoming)
    #  - Permitir 22/tcp, 80/tcp, 443/tcp
    #
    # CORRECTO si:
    #  - ufw está instalado
    #  - ufw status verbose devuelve "Status: active"
    #  - contiene "Default: deny (incoming)"
    #  - existen líneas específicas:
    #       22/tcp  ALLOW IN
    #       80/tcp  ALLOW IN
    #       443/tcp ALLOW IN
    #
    # NOTA:
    #  No vale solo "22/tcp" y "ALLOW IN" por separado: deben estar en la misma línea.
    # ==========================================================

    - name: "[Prueba 3] Comprobar ufw instalado"
      command: dpkg -s ufw
      register: ufw_pkg
      failed_when: false
      changed_when: false

    - name: "[Prueba 3] ufw status verbose (si ufw instalado)"
      command: ufw status verbose
      register: ufw_status
      when: ufw_pkg.rc == 0
      failed_when: false
      changed_when: false

    - name: "[Prueba 3] Normalizar salida ufw (quitar \\r, compactar espacios)"
      set_fact:
        ufw_text: >-
          {{
            (ufw_status.stdout | default(''))
            | replace('\r', '')
            | regex_replace('[ \t]+', ' ')
          }}
      when: ufw_pkg.rc == 0
      changed_when: false

    - name: "[Prueba 3] Guardar resultado"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '3': {
                'name': 'ufw: active + deny incoming + allow 22/80/443',
                'ok': (
                  (ufw_pkg.rc == 0)
                  and ((ufw_status.rc | default(1)) == 0)
                  and ('Status: active' in ufw_text)
                  and ('Default: deny (incoming)' in ufw_text)
                  and ('22/tcp' in ufw_text and 'ALLOW IN' in ufw_text)
                  and ('80/tcp' in ufw_text and 'ALLOW IN' in ufw_text)
                  and ('443/tcp' in ufw_text and 'ALLOW IN' in ufw_text)
                )
              }
            })
          }}
      changed_when: false

    # ==========================================================
    # PRUEBA 4 - DNS de respaldo (1.1.1.1)
    #
    #
    # comprobamos /etc/resolv.conf.
    #
    # CORRECTO si:
    #  - /etc/resolv.conf contiene "nameserver 1.1.1.1"
    # ==========================================================
    - name: "[Prueba 4] Leer /etc/resolv.conf"
      slurp:
        path: /etc/resolv.conf
      register: resolv_conf
      failed_when: false
      changed_when: false

    - name: "[Prueba 4] Decodificar resolv.conf"
      set_fact:
        resolv_text: "{{ (resolv_conf.content | default('') | b64decode) }}"
      changed_when: false

    - name: "[Prueba 4] Guardar resultado (simple)"
      set_fact:
        checks: >-
          {{
            checks | combine({
              '4': {
                'name': 'DNS respaldo: nameserver 1.1.1.1 en /etc/resolv.conf',
                'ok': ('nameserver 1.1.1.1' in (resolv_text | default('')))
              }
            })
          }}
      changed_when: false

    # ==========================
    # SCORE FINAL
    # Se calcula el total de pruebas, el numero de pruebas correctas y el porcentaje obtenido
    # ==========================
    - name: Calcular score final
      set_fact:
        total_checks: "{{ checks | length }}"
        passed_checks: "{{ (checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int }}"
        percent_score: >-
          {{
            (
              ((checks | dict2items | selectattr('value.ok','equalto',true) | list | length) | int) * 100
              / ((checks | length) | int if ((checks | length) | int) > 0 else 1)
            ) | round(0) | int
          }}
      changed_when: false

    - name: Mostrar resultados (resumen)
      debug:
        msg:
          - "Tema: {{ tema_id }} Host: {{ inventory_hostname }}"
          - "{% for item in (checks | dict2items | sort(attribute='key')) %}Prueba {{ item.key }} ({{ item.value.name }}): {{ 'CORRECTO' if item.value.ok else 'INCORRECTO' }}{% if not loop.last %}\n{% endif %}{% endfor %}"
          - "SCORE: {{ passed_checks }}/{{ total_checks }} ({{ percent_score }}%)"

    # ==========================
    # EXPORTAR CSV en AUDITORA
    # Se exportan los resultados a CSV en la maquina auditora usando un script
    # ==========================
    - name: Exportar CSV en la máquina auditora
      import_tasks: /home/tfg-audit/hosts/export_csv.yml
      vars:
        checks: "{{ checks }}"
        passed_checks: "{{ passed_checks }}"
        total_checks: "{{ total_checks }}"
        percent_score: "{{ percent_score }}"
